pipeline{
    agent {
        label 'king'
    }
tools {
  maven 'maven'
}
    stages{
        stage ('checkout'){
            agent {
                docker {
                    image 'narendra98/git:1.0'
                    reuseNode true
                }
            }
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/narendr13/discovery.git']])
                }
            }
        }
    }
}
