pipeline{
    agent {
        label 'king'
    }
tools {
  maven 'maven'
}
    stages{
        stage ('checkout'){
            agent {
                docker {
                    image 'narendra98/git:1.0'
                    reuseNode true
                }
            }
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/narendr13/discovery.git']])
                }
            }
        }
        stage ('king2'){
            agent {
                docker {
                    image 'narendra98/git:3.0'
                    reuseNode true
                }
            }
            steps{
                script{
                    def mvnHome = tool 'maven'
                    def mvnCmd = "${mvnHome}/bin/mvn"
                    sh "${mvnCmd} -f discovery-server/pom.xml clean install"
                }
            }
        }
    }
}
